### ISSUE TITLE
Support for personal projects

### ISSUE THREAD

**Issue by Coder206** [jankeromnes/janitor#20]
I am working on a website with some teammates, it would be nice to have access to the services of The Janitor to enhance the experience for everyone :) 

@jankeromnes Great initiative, love this idea! :)

**Comment by jankeromnes** [comment]
Thank you @Coder206 for the feedback and suggestion!

I'd love to let users add personal projects at some point, but it's a bit too early for that (adding a project to the Janitor is pretty quick, but it requires writing a Dockerfile for that project, and there are some integration steps I need to perform as well).

For website projects however, you can probably use https://c9.io directly, and benefit from all the cool features of their IDE. I think that using Janitor for web apps is a bit overkill (for example, I'm developing the Janitor on Cloud9 directly, not on the Janitor itself, because it's a pretty simple Node.js web app).
