### ISSUE TITLE
Put The Janitor in The Janitor

### ISSUE THREAD

**Issue by notriddle** [jankeromnes/janitor#31]
* I've done developing with your own developer tools, and if nothing else it gives you rapid feedback on all the problems. You will fix all the annoying crap just to be able to not deal with it yourself.

* The most painful part of setting up dev environments for webapps like this is dealing with the external services like GitHub that you can't just host yourself. If you can automate all the setup work needed for a developer instance of an app that runs on GitHub, I'd be very interested in getting [aelita](https://github.com/AelitaBot/aelita) running on janitor.

* I want to be able to run the Janitor in the Janitor so I can code while I code.

**Comment by jankeromnes** [comment]
Great idea! Thanks, added to #24. I remember @sylvestre and @Coder206 also requested this. I used to think it didn't make sense, because the Janitor web app was fairly simple (so better suited for vanilla Cloud9 IDE development, rather than full fledged Docker automation on Janitor), but it is becoming more complex now as it grows to multiple servers, plus setting it up for local development already takes several non-trivial steps, and I definitely agree about the dogfooding benefits in general.

**Comment by jankeromnes** [comment]
This is now live! 🎉🎆🍾
